# Generated by Django 3.0.3 on 2020-02-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowsay',
            name='change_cow',
            field=models.CharField(choices=[('default', 'default'), ('skeleton', 'skeleton'), ('stegosaurus', 'stegosaurus'), ('tux', 'tux'), ('ghostbusters', 'ghostbusters'), ('bong', 'bong'), ('flaming-sheep', 'flaming-sheep'), ('dragon-and-cow', 'dragon-and-cow')], default='default', max_length=15, null=True),
        ),
    ]
